[package]
name = "rpaudio"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.0", features = ["full"] }
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime"] }
rodio = "0.19.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "rpaudio"


[features]
default = ["pyo3/extension-module"]