[package]
name = "rpaudio"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
rodio = "0.19.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "rpaudio"